INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('object',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('fashion',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('clothes',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('workwear',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('protective equipment',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('health',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('medicine',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('medical equipment',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('communication',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('language',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('verb',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('medical procedure',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('movement',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('traffic',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('mode of transport',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('land transport',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('prevention measure',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('nursing equipment',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('cleaning product',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('religion',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('christianity',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('document',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('trade',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('medical test',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('place',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('building',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('work',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('tertiary sector',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('financial services',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('economy',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('money',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('foreign currency',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('feeding',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('food',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('processed food',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('judaism',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('alphabet',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('letter',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('furniture',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('hygiene product',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('hygiene',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('corporal hygiene',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('professional',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('transport services',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('adverb',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('adverb of place',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('education',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('educational organization',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('psychology',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('human response',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('character',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('comic character',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('comic',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('movie character',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('cinema',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('appliance',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('electrical appliance',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('home',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('defense',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('security',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('supporting document',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('educational material',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('augmentative communication',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sociology',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('social movement',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('medical center',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('person',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('child',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('disruptive behavior',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('pronoun',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('interrogative pronoun',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('time',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('calendar',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('day',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('event',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('group',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('animal-based food',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('meat',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('accessories',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('leisure',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('toy',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('meteorology',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('atmospheric phenomena',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('psychomotor equipment',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('footwear',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sport',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sport material',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('music',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('musical instrument',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('percussion instrument',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('human body',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('popular event',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('carnival',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('household',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('trousseau',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('geography',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('political geography',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('flag',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('country',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('gastronomy',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('traditional dish',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('traditional game',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('air transport',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('scenic art',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('dance',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('regional dance',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('show',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('water transport',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('special education',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('infrastructure',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('facility',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('book character',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('tale character',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('literature',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sports facility',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('signaling system',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('ultra-processed food',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('physiotherapy equipment',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('plant-based food',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('vegetable',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('cutlery',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('architecture',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('architectural element',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('costume',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('cosmetic',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('personal services',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('mathematics',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sport modality',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sports',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('islamism',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('monument',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('fruit',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sport event',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('mass media',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('medical device',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('expression',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('polite set expression',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('adjective',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('indefinite adjective',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('medicament',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('dessert',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('baking',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('regional costume',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sexuality',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('gender identity',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('computing',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('hardware',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('communication aid',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('catering establishment',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('hospitality industry',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('orthopedic product',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sportswear',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('clothing',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sensory stimulation',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('game',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('educational task',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('crockery',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('plant',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('flower',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('subject',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('cactus',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sweets',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('religious event',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('christmas',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('biology',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('utensil',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('educational equipment',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('communication system',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('urban area',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('culture',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('athlete',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('elderly',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('adapted sport',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('fiestas del pilar',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('string instrument',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('olympic games',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('street furniture',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('theater',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('disease',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('industry',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('educational space',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('animal',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('circus',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('material',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('raw material',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('mineral origin material',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('month',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('recreational facility',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('secondary sector',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('construction',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('terrestrial animal',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('flying animal',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('aquatic animal',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('marine animal',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sea',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('city',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('spices',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('symptom',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('beverage',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('history',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('archaeology',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('dairy product',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('fungus',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('condiment',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('number',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('wind instrument',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('fish',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('anatomy',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('animal anatomy',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('educational institution',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('emotion',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('qualifying adjective',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('physiotherapy',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('spain region',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('easter week',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('board game',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('law',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('justice',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('extinct being',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('dinosaur',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('dinosaur anatomy',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('fossil',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('paleontology',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('bush',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('seafood',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('manufacturing industry',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('vehicle component',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('tool',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('omnivorous',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('invertebrate',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('mollusc',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('oviparous',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('tree',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('carnivorous',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('vertebrate',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('bird',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('odontology',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('family',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('dried fruit',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('coin',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('visual art',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sculpture',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('astronomy',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('historical character',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('herbivorous',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('reptile',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('cold meat',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('natural disaster',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('animal housing',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('physical geography',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('landform',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('river',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('energy',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('mass media device',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('animal physiology',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('primary sector',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('agriculture',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('cereal',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('orthographic sign',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('ovoviviparous',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('freshwater animal',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('crime',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sexual crime',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('continent',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sexual practice',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('light fixture',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('color',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('legal institution',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('ordinal adjective',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('waste disposal',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('mammal',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('viviparous',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('amphibian',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('region',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('taste',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('adverb of denial',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('prehistory',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('plant anatomy',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('human reproduction',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('professional services',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('consultancy',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('baby',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('shape',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('geometry',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('egg product',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('arthropod',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('crustacean',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('physiology',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('human physiology',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('respiratory system',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('room',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('ocean',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('occupational therapy',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('human anatomy',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('senses',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('unit of time',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sexual orientation',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('oceanography',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('ancient history',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('interjection',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('adverb of time',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('plant physiology',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('political representation',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('new year',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('cattle farming',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('forestry',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('road safety',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('traffic signal',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('feeling',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('personal pronoun',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('human value',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('reproductive system',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('contraceptive method',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('adverb of affirmation',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('digestive system',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('chronological device',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('craftsmanship',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('traffic accident',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('telecommunication',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('adverb of degree',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('jewelry',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('it',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('information technology',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('tourism',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('musical notation',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('musical composition',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('annelid',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('conjunction',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('conditional conjunction',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('photography',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('insect',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('opera',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('mythological character',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('mythology',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('indefinite pronoun',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('legume',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('excretory system',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('keyboard instrument',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('mining',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('teenager',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('work machine',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('adverb of manner',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('video game',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('mineral rich food',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('osseous system',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('muscular system',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('painting',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('locomotor system',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('gender violence',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('the falles',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('preposition',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('adult',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('season',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('spring',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('spain province',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('joint system',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('hinduism',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('leader',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('environmental science',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('nervous system',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('buddhism',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('aromatic plant',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('route',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('gambling',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('publication',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('possessive adjective',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('possessive pronoun',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('demonstrative adjective',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('article',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('marital status',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('copulative conjunction',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('teaching activity',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('veterinary medicine',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('bullfighting',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('adversative conjunction',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('causal conjunction',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('fishing',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('sport rules',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('dietetics',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('concessive conjunction',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('circulatory system',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('apiculture',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('province',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('arachnid',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('bill',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('onomatopoeia',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('fossil origin material',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('set phrase',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('animal material',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('derived material',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('halloween',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('vegetal origin material',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('summer',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('natural habitat',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('autumn',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('winter',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('size',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('echinoderm',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('card game',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('coelenterata',1)
INSERT INTO [dbo].[Etiqueta]             ([nombre]             ,[activo])       VALUES             ('integumentary system',1)